"""add_time_attendees_outcomes_to_interactions

Revision ID: 583d8fa8703e
Revises: c0c3b5ec7928
Create Date: 2026-05-01 06:51:19.400395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '583d8fa8703e'
down_revision: Union[str, Sequence[str], None] = 'c0c3b5ec7928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('time', sa.String(length=10), nullable=True))
    op.add_column('interactions', sa.Column('attendees', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('interactions', sa.Column('outcomes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'outcomes')
    op.drop_column('interactions', 'attendees')
    op.drop_column('interactions', 'time')
    # ### end Alembic commands ###
