"""init auto generated model

Revision ID: c0c3b5ec7928
Revises: 
Create Date: 2026-04-22 11:59:42.306254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0c3b5ec7928'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('hcp_id', sa.UUID(), nullable=True),
    sa.Column('messages_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_session_id'), 'agent_sessions', ['session_id'], unique=True)
    op.create_table('hcps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('hospital', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.Enum('tier1', 'tier2', 'tier3', name='hcp_tier_enum'), server_default='tier2', nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.Enum('visit', 'call', 'email', 'conference', name='interaction_type_enum'), server_default='visit', nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('products_discussed', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='interaction_sentiment_enum'), server_default='neutral', nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('entities_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('hcp_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'cancelled', name='follow_up_status_enum'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_ups')
    op.drop_table('interactions')
    op.drop_table('hcps')
    op.drop_index(op.f('ix_agent_sessions_session_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
